# Generated by Django 5.2.4 on 2025-07-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
    ]
