# Generated by Django 5.2.4 on 2025-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
