# Generated by Django 5.2.4 on 2025-07-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
