# Generated by Django 5.2.4 on 2025-07-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
    ]
