# Generated by Django 5.2.4 on 2025-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
