# Generated by Django 5.2.4 on 2025-07-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_delete_customeraddress'),
        ('orders', '0007_order_status_alter_order_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.address'),
        ),
    ]
