# Generated by Django 5.2.4 on 2025-07-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_image'),
        ('shops', '0003_shop_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('name', 'shop')},
        ),
    ]
