# Generated by Django 5.2.4 on 2025-07-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='images/default.jpeg', null=True, upload_to='images/'),
        ),
    ]
