# Generated by Django 5.2.4 on 2025-07-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_image'),
        ('shops', '0006_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='shops.shop'),
            preserve_default=False,
        ),
    ]
