# Generated by Django 5.2.4 on 2025-07-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menuitem_shop'),
        ('shops', '0006_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
