# Generated by Django 5.2.4 on 2025-07-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menuitemoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemoption',
            name='item',
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.menucategory'),
        ),
    ]
